services:
  mongodb:
    image: mongo
    restart: always
    environment:
      - MONGO_INITDB_DATABASE=authors
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=pass
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
  flask:
    build: .
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - mongodb